// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'firebase_options.dart';
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKaH1bp3Gb9la7zhM12sFOaZuw3NK8n9M',
    appId: '1:909429677253:web:a0956fe4563f23ccfd64ac',
    messagingSenderId: '909429677253',
    projectId: 'hora-do-rango',
    authDomain: 'hora-do-rango.firebaseapp.com',
    storageBucket: 'hora-do-rango.appspot.com',
    measurementId: 'G-7D26MKBL7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrwp0L5v-sYwU7hqjCiaFK37U0cSIpXaE',
    appId: '1:909429677253:android:d9d5163523d84492fd64ac',
    messagingSenderId: '909429677253',
    projectId: 'hora-do-rango',
    storageBucket: 'hora-do-rango.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOpKbdXOshJMfTDAQlrCB_zOBqpEjz0Mk',
    appId: '1:909429677253:ios:400f52e0f3c3afe9fd64ac',
    messagingSenderId: '909429677253',
    projectId: 'hora-do-rango',
    storageBucket: 'hora-do-rango.appspot.com',
    iosClientId: '909429677253-2ktihb8meuki1fa3j1n3mldhbgl7u4kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
